services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    restart: unless-stopped
    ports:
      - 8610:6333
      - 8611:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - vaults_services_network
  vector_kb_service:
    build: vector_kb_service
    restart: unless-stopped
    volumes:
      - ./vector_kb_service:/usr/src/vector_kb_service
    env_file:
      ./vector_kb_service/.env
    ports:
      - 8600:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/vector_kb_service/uvicorn_logging.conf"
    networks:
      - vaults_services_network
  vector_rag_service:
    build: vector_rag_service
    restart: unless-stopped
    env_file:
      ./vector_rag_service/.env
    volumes:
      - ./vector_rag_service:/usr/src/vector_rag_service
    ports:
     - 8700:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/vector_rag_service/uvicorn_logging.conf"
    networks:
      - vector_rag_service_network
      - vaults_services_network
      - papper-backend

volumes:
  qdrant_storage:

networks:
  vaults_services_network:
    name: vaults_services_network
  vector_rag_service_network:
    name: vector_rag_service_network
  papper-backend:
    name: papper-backend
    external: true
